### ISSUE TITLE
Eclipse Environment Setup on Mac

### ISSUE THREAD

**Issue by aditigaur824** [UCSD-E4E/radio_collar_tracker_gcs#18]
When setting up the Eclipse environment on Mac, there is an additional step required in order to to run rctGCS.py. 

The variable 'PROJ_LIB' needs to be manually defined inside of the eclipse preferences python interpreter settings. 

The screenshots attached detail what the error message looks like and how to resolve the error.

Error Message: 
![Screen Shot 2020-06-10 at 5 28 36 PM](https://user-images.githubusercontent.com/46062701/84716248-6ddce580-af27-11ea-93da-5a881e0c7e86.png)

Resolution: Eclipse->Preferences->Pydev->Python Interpreters->click on rctGCS->click on environment tab->add variable definition for 'PROJ_LIB':
![Screen Shot 2020-06-15 at 4 44 47 PM](https://user-images.githubusercontent.com/46062701/84716331-a7155580-af27-11ea-8404-b1806b530d77.png)

**Comment by ntlhui** [comment]
Which MacOS version?  Can you also add the output of `conda list -n rctGCS`
