### ISSUE TITLE
Polygon shape doesn't clear after exporting

### ISSUE THREAD

**Issue by mlucio123** [UCSD-E4E/radio_collar_tracker_gcs#30]
To recreate bug:
Define area with polygon map tool
click "Polygon" under "Export" tab
choose folder to save shapefiles
click "Clear Map" button

**Comment by hgrehm** [comment]
resolved with https://github.com/UCSD-E4E/radio_collar_tracker_gcs/pull/54/commits/a0d77e89093e3f89d636daf1430684e4fdc4a3f7
