### ISSUE TITLE
Component connection status

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker_gcs#42]
### Commit Hash

340666d475c13666e46f3b07f6ca825466e769e9

### Steps to Reproduce?

Connect to payload, open components drop-down

### Observed Behavior

Status still reads disconnected

### Desired Behavior

Status should reflect connection status

**Comment by hgrehm** [comment]
I'm seeing this in tower_drone_integration_HG, yes. I can check other HG branches but am guessing they will be outdated. Will look into it.

**Comment by ntlhui** [comment]
@hgrehm Recommend we branch off of e6db4d to create a fix for this specifically and merge to communications_HG and drome_based_MD.

**Comment by hgrehm** [comment]
resolved with https://github.com/UCSD-E4E/radio_collar_tracker_gcs/commit/b4ea6499921a31a6aefdc18b014386300cb1df74
