### ISSUE TITLE
System Options Validation in UI

### ISSUE THREAD

**Issue by aditigaur824** [UCSD-E4E/radio_collar_tracker_gcs#7]
System options such as "center frequency" should be validated so the user cannot simply enter a garbage value. This should be done in some form on the UI, not simply the terminal.

**Comment by ntlhui** [comment]
CU-bcn204

**Comment by hgrehm** [comment]
Resolved with [46ed280](https://github.com/UCSD-E4E/radio_collar_tracker_gcs/commit/46ed280ea3c9687f5530bca6d22205eb37894f8b)
